window.REMITTANCE_DATA = [
  {
    "provider": "센트비",
    "type": "핀테크 해외송금",
    "country": "베트남",
    "channel": "온라인/앱",
    "fee": "확인예정",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "익스프레스: 당일 / 스탠다드: +2~3 영업일",
    "receive_method": "현지 은행계좌",
    "promotion": "",
    "source": "센트비 공식 홈페이지·고객센터",
    "checked_at": "2026-09-01",
    "notes": ""
  },
  {
    "provider": "SBI 코스머니",
    "type": "핀테크 해외송금",
    "country": "베트남",
    "channel": "온라인/앱",
    "fee": "확인예정",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "최소 1분 ~ 최대 1일",
    "receive_method": "해외송금 / 세부 수취방식 추가 확인 필요",
    "promotion": "",
    "source": "SBI 코스머니 공식 홈페이지",
    "checked_at": "2026-09-01",
    "notes": ""
  },
  {
    "provider": "GME Remittance",
    "type": "핀테크 해외송금",
    "country": "베트남",
    "channel": "온라인/앱",
    "fee": "확인예정",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "확인필요",
    "receive_method": "계좌이체",
    "promotion": "",
    "source": "GME Remittance 공식 홈페이지",
    "checked_at": "2026-09-01",
    "notes": ""
  },
  {
    "provider": "한패스",
    "type": "핀테크 해외송금",
    "country": "베트남",
    "channel": "온라인/앱",
    "fee": "5000",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "약 15분",
    "receive_method": "계좌이체",
    "promotion": "",
    "source": "한패스 공식 홈페이지 송금 계산기",
    "checked_at": "2026-09-01",
    "notes": ""
  },
  {
    "provider": "한패스",
    "type": "핀테크 해외송금",
    "country": "중국",
    "channel": "온라인/앱",
    "fee": "0",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "당일",
    "receive_method": "계좌이체",
    "promotion": "",
    "source": "한패스 공식 홈페이지 송금 계산기",
    "checked_at": "2026-09-01",
    "notes": ""
  },
  {
    "provider": "한패스",
    "type": "핀테크 해외송금",
    "country": "태국",
    "channel": "온라인/앱",
    "fee": "5000",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "현지 환경에 따라",
    "receive_method": "계좌이체",
    "promotion": "",
    "source": "한패스 공식 홈페이지 송금 계산기",
    "checked_at": "2026-09-02",
    "notes": ""
  },
  {
    "provider": "한패스",
    "type": "핀테크 해외송금",
    "country": "필리핀",
    "channel": "온라인/앱",
    "fee": "5000",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "약 1일",
    "receive_method": "계좌이체",
    "promotion": "",
    "source": "한패스 공식 홈페이지 송금 계산기",
    "checked_at": "2026-09-03",
    "notes": ""
  },
  {
    "provider": "한패스",
    "type": "핀테크 해외송금",
    "country": "인도네시아",
    "channel": "온라인/앱",
    "fee": "5000",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "약 15분",
    "receive_method": "계좌이체",
    "promotion": "",
    "source": "한패스 공식 홈페이지 송금 계산기",
    "checked_at": "2026-09-04",
    "notes": ""
  },
  {
    "provider": "한패스",
    "type": "핀테크 해외송금",
    "country": "캄보디아",
    "channel": "온라인/앱",
    "fee": "5000",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "약 15분",
    "receive_method": "계좌이체",
    "promotion": "",
    "source": "한패스 공식 홈페이지 송금 계산기",
    "checked_at": "2026-09-05",
    "notes": ""
  },
  {
    "provider": "은행 1곳",
    "type": "은행 송금",
    "country": "베트남",
    "channel": "온라인/앱",
    "fee": "확인예정",
    "extra_fee": "",
    "exchange_rate": "확인예정",
    "receive_amount": "확인예정",
    "transfer_time": "",
    "receive_method": "",
    "promotion": "",
    "source": "",
    "checked_at": "",
    "notes": ""
  },
  {
    "provider": "iM뱅크(구 대구은행)",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액이하   :  5,000원 / 미화 2,000불 상당액이하 : 10,000원 / 미화 5,000불 상당액이하 : 15,000원 / 미화 20,000불 상당액이하: 20,000원 / 미화 20,000불 상당액초과: 25,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "SC제일은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "건당 미화 2천불이하 : 7,000 / 건당 미화 4천불이하 : 10,000  / 건당 미화 6천불이하 : 12,000  / 건당 미화 8천불이하 : 15,000  / 건당 미화 1만불이하 : 18,000  / 건당 미화 2만불이하 : 20,000  / 건당 미화 4만불이하 : 25,000  / 건당 미화 4만불초과 : 30,000",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "한국씨티은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "U$1천불이하 7,000원 / U$5천불이하 12,000원  / U$5천불초과 23,000원 / U$5만불초과 30,000원",
    "extra_fee": "(건당)8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "하나은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "(외화송금) / 미화 500불 상당액 이하 : 5,000원 / 미화 2,000불 상당액 이하 : 10,000원 / 미화 5,000불 상당액 이하 : 15,000원 / 미화 20,000불 상당액 이하 : 20,000원 / 미화 20,000불 상당액 초과 : 25,000원 /  / (해외 원화송금) / 1천만원 이하 : 30,000원 / 5천만원 이하 : 40,000원 / 1억원 이하 : 50,000원 / 5억원 이하 : 70,000원 / 5억원 초과 : 100,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "신한은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 5백불 상당액 이하:  5,000원 / 미화 2천불 상당액 이하: 10,000원 / 미화 5천불 상당액 이하: 15,000원 / 미화 2만불 상당액 이하: 20,000원 / 미화 2만불 상당액 초과: 25,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "우리은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액 이하: 5,000원 / 미화 2,000불 상당액 이하: 10,000원 / 미화 5,000불 상당액 이하: 15,000원 / 미화 20,000불 상당액 이하: 20,000원 / 미화 20,000불 상당액 초과: 25,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "KB국민은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액 이하 : 5,000원 / 미화 2,000불 상당액 이하 : 10,000원 / 미화 5,000불 상당액 이하 : 15,000원 / 미화 10,000불 상당액 이하 : 20,000원 / 미화 10,000불 상당액 초과 : 25,000원 / [개인KB스타클럽] / VVIP,VIP : 면제 / 그랜드 : 50%감면 / [법인KB스타클럽] / VVIP : 면제 / VIP : 50%감면",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "SC제일은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "신 기업인터넷뱅킹 (S2B NextGen) / - 건당 미화 5천불 이하: 10,000원 / - 건당 미화 5천불 초과: 20,000원",
    "extra_fee": "전신료 8,000원 별도",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "하나은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "미화 5,000불 상당액 이하 : 3,000원 / 미화 5,000불 상당액 초과 : 5,000원",
    "extra_fee": "(건당) 5,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "iM뱅크(구 대구은행)",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "창구수수료의 50%",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "우리은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "- 창구송금수수료의 50% 우대 / *개인고객만 해당(단, 기업고객의 경우 창구송금수수료와 동일) / *우리가족우대서비스 등급 해당고객은 면제 / - 별도 통지시까지 개인고객 수수료 우대 / 미화 500불 상당액 이하: 2,500원  / 미화 3,000불 상당액 이하: 5,000원 / 미화 5,000불 상당액 이하 : 7,500원 / 미화 5,000불 상당액 초과 : 10,000",
    "extra_fee": "(건당) 8,000원 /  / - 별도 통지시까지 개인고객 송금시 전신료 면제",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "한국씨티은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "인터넷뱅킹(개인) : 면제 / 인터넷뱅킹(법인) : 7,000",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "신한은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "미화 5백불 상당액 이하:  2,500원 / 미화 2천불 상당액 이하:  5,000원 / 미화 5천불 상당액 이하:  7,500원 / 미화 2만불 상당액 이하: 10,000원 / 미화 2만불 상당액 초과: 12,500원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "KB국민은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "미화 5,000불 상당액 이하 : 3,000원 / 미화 5,000불 상당액 초과 : 5,000원 / [개인KB스타클럽] / VVIP,VIP : 면제 / 그랜드 : 50%할인 / [법인KB스타클럽] / VVIP : 면제 / VIP : 50%할인 / 자동화기기(ATM) 해외송금 : 면제",
    "extra_fee": "(건당) 5,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "SC제일은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "[개인 모바일 뱅킹] /  - (국내에서 해외로)당발송금수수료: 100% 면제 / [개인 인터넷 뱅킹] /  - (국내에서 해외로)당발송금수수료: 100% 면제 / [기업 인터넷 뱅킹] BBP(Business Banking platform) /  - (국내에서 해외로) 당발송금수수료: 창구수수료와 동일",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "BNK부산은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액 이하 : 5,000원 / 미화 2,000불 상당액 이하 : 10,000원 / 미화 5,000불 상당액 이하 : 15,000원 / 미화 10,000불 상당액 이하 : 20,000원 / 미화 10,000불 상당액 초과 : 25,000원",
    "extra_fee": "(건당)8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "BNK경남은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 5백불 상당액 이하: 5,000원 / 미화 2천불 상당액 이하: 10,000원 / 미화 5천불 상당액 이하: 15,000원 / 미화 1만불 상당액 이하: 20,000원 / 미화 1만불 상당액 초과: 25,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "광주은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액 이하 : 5,000원 / 미화 2,000불 상당액 이하 : 10,000원 / 미화 5,000불 상당액 이하 : 15,000원 / 미화 10,000불 상당액 이하 : 20,000원 / 미화 10,000불 상당액 초과 : 25,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "제주은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화2,000불 상당액 이하 : 5,000원 / 미화5,000불 상당액 이하 : 10,000원 / 미화 5,000불 상당액 초과 : 15,000원",
    "extra_fee": "(건당)5000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "전북은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액이하 : 5,000원 / 미화 2,000불 상당액이하 : 10,000원 / 미화 5,000불 상당액이하 : 15,000원 / 미화 20,000불 상당액이하 : 20,000원 / 미화 20,000불 상당액초과 : 25,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "BNK경남은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "미화 5백불 상당액 이하: 2,500원  / 미화 2천불 상당액 이하: 5,000원  / 미화 5천불 상당액 이하: 7,500원  / 미화 1만불 상당액 이하: 10,000원  / 미화 1만불 상당액 초과: 12,500원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "전북은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "(개인) : 면        제 /  / (기업인터넷해외송금서비스) / 미화 500불 상당액이하 : 5,000원  / 미화 2,000불 상당액이하 : 8,000원  / 미화 5,000불 상당액이하 : 13,000원  / 미화 5,000불 상당액 초과 : 18,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "광주은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "창구송금수수료의 50%우대 / (금융상품우대율이 더 높은경우, 높은우대율 적용됨)",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "BNK부산은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "미화 500불 상당액 이하 : 5,000원 / 미화 2,000불 상당액 이하 : 10,000원 / 미화 5,000불 상당액 이하 : 15,000원 / 미화 10,000불 상당액 이하 : 20,000원 / 미화 10,000불 상당액 초과 : 25,000원",
    "extra_fee": "(건당)3,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "제주은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "개인:면제",
    "extra_fee": "(건당)5,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "NH농협은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액 이하 : 5,000원 / 미화 2,000불 상당액 이하 : 10,000원 / 미화 5,000불 상당액 이하 : 15,000원 / 미화 20,000불 상당액 이하 : 20,000원 / 미화 20,000불 상당액 초과 : 25,000원",
    "extra_fee": "(건당) 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "IBK기업은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "미화 500불 상당액 이하 : 5,000원  / 미화 2,000불 상당액 이하 : 10,000원  / 미화 5,000불 상당액 이하 : 15,000원  / 미화 5,000불 상당액 초과 : 20,000원",
    "extra_fee": "(건당)8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "Sh수협은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "USD 5백불 이하 : 5천원  / USD 5백불 초과 ~ 2천불 이하 : 1만원 / USD 2천불 초과 ~ 5천불 이하 : 1만2천원 / USD 5천불 초과 ~ 1만불 이하 : 1만5천원 / USD 1만불 초과 : 2만원",
    "extra_fee": "건당 8,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "한국산업은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "창구",
    "fee": "기준 : 송금액 X 환율(매매기준율) X 0.05% / 최고 : 20,000원 / 최소 :  5,000원",
    "extra_fee": "(전문건당) 5,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "NH농협은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "미화 5,000불 상당액 이하 : 3,000원  / 미화 5,000불 상당액 초과 : 5,000원",
    "extra_fee": "(건당) 5,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "Sh수협은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "USD 5천불 이하 : 3천원  / USD 5천불 초과 : 5천원 /  / (단, 인터넷해외송금(기업전용) 서비스는 창구 해외송금수수료와 동일)",
    "extra_fee": "건당 8,000원 / (단, 모바일 해외송금 건당 5,000원)",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "한국산업은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "기준 : 송금액 X 환율(매매기준율) X 0.05% / 최고 : 20,000원 / 최소 :  5,000원",
    "extra_fee": "(전문건당) 5,000원",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "IBK기업은행",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "(개인) 수수료 면제(유학경비,증빙서류미제출,외국인국내보수 사유로 원화통장에서 출금하여 송금 시) /  / (기업) 인터넷무역대전 및 무역외송금 / 미화 500불상당액 이하 2,500원  / 미화 2,000불상당액 이하 5,000원 / 미화 5,000불상당액 이하 7,500원 / 미화 5,000불상당액 초과 10,000원 /  / (공통)외화통장 출금 시 당발송금수수료(창구)와 동일",
    "extra_fee": "(건당) 8,000원,  / (건당) 5,000원 - 개인고객에 한함(인터넷·스마트뱅킹, ATM, ARS, ANYTIME)",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "케이뱅크",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "* 모바일에서만 송금 가능 /  / ■ 해외계좌송금 /  - 3,500원 /   / ■ 머니그램 해외송금  /  - 건당 USD 4",
    "extra_fee": "없음",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "카카오뱅크",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "■해외계좌송금 / (원화로 보낼때) 4,900원 / (외화로 보낼때) 4,900원에 해당하는 송금통화 + 송금액의 0.5% /  / ■WU빠른해외송금 / (원화로 보낼때) USD 5 / (외화로 보낼때) USD 5 + 송금액의 1.0%",
    "extra_fee": "-",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "토스뱅크",
    "type": "은행 해외송금",
    "country": "공통",
    "channel": "인터넷",
    "fee": "■해외계좌송금 / - (총 30개국) 미국, 캐나다, 호주, 영국, 싱가포르, 홍콩, 유로를 사용하는 유럽연합 국가 / - 송금액에 관계 없이 건당 3,900원",
    "extra_fee": "없음",
    "exchange_rate": "송금 시 확인",
    "receive_amount": "송금 시 확인",
    "transfer_time": "확인 필요",
    "receive_method": "해외 은행계좌",
    "promotion": "",
    "source": "전국은행연합회 외환수수료 비교공시",
    "checked_at": "2026-09-01",
    "notes": "은행별 실제 환율 및 해외 중개·수취은행 수수료는 송금 시 추가 확인 필요"
  },
  {
    "provider": "센트비",
    "type": "핀테크 해외송금",
    "country": "중국",
    "channel": "온라인/앱",
    "fee": "앱에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "센트비 공식 홈페이지·고객센터",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 송금 단계에서 재확인 필요."
  },
  {
    "provider": "센트비",
    "type": "핀테크 해외송금",
    "country": "태국",
    "channel": "온라인/앱",
    "fee": "앱에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "센트비 공식 홈페이지·고객센터",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 송금 단계에서 재확인 필요."
  },
  {
    "provider": "센트비",
    "type": "핀테크 해외송금",
    "country": "필리핀",
    "channel": "온라인/앱",
    "fee": "앱에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "센트비 공식 홈페이지·고객센터",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 송금 단계에서 재확인 필요."
  },
  {
    "provider": "센트비",
    "type": "핀테크 해외송금",
    "country": "인도네시아",
    "channel": "온라인/앱",
    "fee": "앱에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "센트비 공식 홈페이지·고객센터",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 송금 단계에서 재확인 필요."
  },
  {
    "provider": "센트비",
    "type": "핀테크 해외송금",
    "country": "캄보디아",
    "channel": "온라인/앱",
    "fee": "앱에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "센트비 공식 홈페이지·고객센터",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 송금 단계에서 재확인 필요."
  },
  {
    "provider": "SBI 코스머니",
    "type": "핀테크 해외송금",
    "country": "중국",
    "channel": "온라인/앱",
    "fee": "송금 단계에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "최소 1분 ~ 최대 1일",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "SBI 코스머니 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 국가·수취방식에 따라 세부 조건이 달라질 수 있음."
  },
  {
    "provider": "SBI 코스머니",
    "type": "핀테크 해외송금",
    "country": "태국",
    "channel": "온라인/앱",
    "fee": "송금 단계에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "최소 1분 ~ 최대 1일",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "SBI 코스머니 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 국가·수취방식에 따라 세부 조건이 달라질 수 있음."
  },
  {
    "provider": "SBI 코스머니",
    "type": "핀테크 해외송금",
    "country": "필리핀",
    "channel": "온라인/앱",
    "fee": "송금 단계에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "최소 1분 ~ 최대 1일",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "SBI 코스머니 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 국가·수취방식에 따라 세부 조건이 달라질 수 있음."
  },
  {
    "provider": "SBI 코스머니",
    "type": "핀테크 해외송금",
    "country": "인도네시아",
    "channel": "온라인/앱",
    "fee": "송금 단계에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "최소 1분 ~ 최대 1일",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "SBI 코스머니 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 국가·수취방식에 따라 세부 조건이 달라질 수 있음."
  },
  {
    "provider": "SBI 코스머니",
    "type": "핀테크 해외송금",
    "country": "캄보디아",
    "channel": "온라인/앱",
    "fee": "송금 단계에서 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "송금 단계에서 확인",
    "receive_amount": "송금 단계에서 확인",
    "transfer_time": "최소 1분 ~ 최대 1일",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "SBI 코스머니 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 국가·수취방식에 따라 세부 조건이 달라질 수 있음."
  },
  {
    "provider": "GME Remittance",
    "type": "핀테크 해외송금",
    "country": "중국",
    "channel": "온라인/앱",
    "fee": "로그인 후 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "로그인 후 확인",
    "receive_amount": "로그인 후 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "GME Remittance 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 로그인 또는 송금 단계에서 확인 필요."
  },
  {
    "provider": "GME Remittance",
    "type": "핀테크 해외송금",
    "country": "태국",
    "channel": "온라인/앱",
    "fee": "로그인 후 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "로그인 후 확인",
    "receive_amount": "로그인 후 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "GME Remittance 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 로그인 또는 송금 단계에서 확인 필요."
  },
  {
    "provider": "GME Remittance",
    "type": "핀테크 해외송금",
    "country": "필리핀",
    "channel": "온라인/앱",
    "fee": "로그인 후 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "로그인 후 확인",
    "receive_amount": "로그인 후 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "GME Remittance 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 로그인 또는 송금 단계에서 확인 필요."
  },
  {
    "provider": "GME Remittance",
    "type": "핀테크 해외송금",
    "country": "인도네시아",
    "channel": "온라인/앱",
    "fee": "로그인 후 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "로그인 후 확인",
    "receive_amount": "로그인 후 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "GME Remittance 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 로그인 또는 송금 단계에서 확인 필요."
  },
  {
    "provider": "GME Remittance",
    "type": "핀테크 해외송금",
    "country": "캄보디아",
    "channel": "온라인/앱",
    "fee": "로그인 후 확인",
    "extra_fee": "확인 필요",
    "exchange_rate": "로그인 후 확인",
    "receive_amount": "로그인 후 확인",
    "transfer_time": "확인 필요",
    "receive_method": "국가별 상이 / 송금 단계에서 확인",
    "promotion": "",
    "source": "GME Remittance 공식 홈페이지",
    "checked_at": "2026-09-02",
    "notes": "해당 국가 송금 지원 확인. 실제 수수료·수취방식·소요시간은 로그인 또는 송금 단계에서 확인 필요."
  }
];
